### ISSUE TITLE
0 tweet recived with date range

### ISSUE THREAD

**Issue by D3f4lt96** [batuhaniskr/twitter-intelligence#10]
Hi¡ 
This tool works perfectly for me, but when i provide a specific date range, i´m getting always 0 tweet recived. Can this be due to the date format? Because i´m from Spain and our date format is d/m/y. 
Can you confirm this? 
Thx.

![captura](https://user-images.githubusercontent.com/42640149/47489963-081a8200-d848-11e8-9ecd-0cc6d2d07428.PNG)
![captura1](https://user-images.githubusercontent.com/42640149/47489964-081a8200-d848-11e8-8573-8abcc9f9c3cd.PNG)

**Comment by batuhaniskr** [comment]
Hi @D3f4lt96,

DateFormat is "y/m/d". You have to try with this format and if you want location based searching, you need Google Map API Key.
