### ISSUE TITLE
 0 tweet received always

### ISSUE THREAD

**Issue by gusleig** [batuhaniskr/twitter-intelligence#9]
I managed to install but I'm getting always 0 tweet received.

any way to debug it?

thanks

**Comment by batuhaniskr** [comment]
@gusleig Can you send me the command when you're running?

Make sure that you install pip3 with the dependencies and python3 with the running application.

**Comment by batuhaniskr** [comment]
Has TweetAnalysis.db named database been created?

**Comment by gusleig** [comment]
Yes, its there.
![image](https://user-images.githubusercontent.com/1760632/46230192-389cf800-c33e-11e8-8110-3eb2eeb4b96d.png)

**Comment by gusleig** [comment]
debugging with pycharm, the problem is with line 

response = opener.open(url)

gets an exception

the value of url is:

url='https://twitter.com/i/search/timeline?f=tweets&q=%20sakarya&src=typd&max_position='

when I open this url in my browser I get a file

**Comment by gusleig** [comment]
Looking to the exception, what it gets:

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

**Comment by gusleig** [comment]
I fixed it using those lines in tweet_operation.py:

import ssl
.
.
.
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

THEN

opener = urllib2.build_opener(urllib2.HTTPSHandler(context=ctx), urllib2.HTTPCookieProcessor(cookiejar))

**Comment by batuhaniskr** [comment]
I am testing Python 3.6.2 and debian based linux distro but I not get this error. Which you use python version?

**Comment by gusleig** [comment]
Tested with linux Ubuntu 16.04.5 LTS and macOS

I just tested today again with a brand new linux installation in my virtual machine, same SSL error, this kind of error happens too when making the Google Map analysis. 

Anyway I managed to fix it with the lines above and others (for the map analysis)  I can share when I get back home from work.

Things I added in my local version that I think its cool.

1. Timestamp to every printed line
2. A tweets per second ratio at the end.

I think your code is great, very helpful.
Thank you very much

**Comment by ahmedjavad** [comment]
@batuhaniskr ,Hi, I have same issue,

**Comment by batuhaniskr** [comment]
> Tested with linux Ubuntu 16.04.5 LTS and macOS
> 
> I just tested today again with a brand new linux installation in my virtual machine, same SSL error, this kind of error happens too when making the Google Map analysis.
> 
> Anyway I managed to fix it with the lines above and others (for the map analysis) I can share when I get back home from work.
> 
> Things I added in my local version that I think its cool.
> 
>     1. Timestamp to every printed line
> 
>     2. A tweets per second ratio at the end.
> 
> 
> I think your code is great, very helpful.
> Thank you very much

@gusleig Thank you so much.

If you want, you can open a pull request.

**Comment by ahmedjavad** [comment]
@batuhaniskr What you means "installed in the Applications folder with the folder name 'Python 3.6'"? I have debian 9 with python3.5

**Comment by batuhaniskr** [comment]
Can you try `pip3 install certifi` command on your environment?

**Comment by ahmedjavad** [comment]
@batuhaniskr . Output : `Requirement already satisfied: certifi in /usr/local/lib/python3.5/dist-packages`

**Comment by ahmedjavad** [comment]
@batuhaniskr Hi, same result,

```python
python3 tracking.py --username "rihanna"
[+] Searching...


[+] 0 tweet received...

[+] Succesfully saved to the database.
```

**Comment by batuhaniskr** [comment]
@ahmedjavad Hi, Do you have a internet connection when you tested this project? 

If there is wrong network settings, it may caused be this result.

**Comment by ahmedjavad** [comment]
>> Do you have a internet connection when you tested this project?

Yes, ^_^.

**Comment by batuhaniskr** [comment]
Sorry, I can not resolved your that situation.

**Comment by devil67** [comment]
Me too [+] Searching...


[+] 0 tweet received...

[+] Succesfully saved to the database.

**Comment by tobozo** [comment]
Same symptoms: I always get the same response (although different order) whatever the query/username:

```
{'min_position': 'cm+55m--', 'focused_refresh_interval': 30000, 'has_more_items': False, 'new_latent_count': 0, 'items_html': '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n'}
```

- System: Ubuntu 16.04
- pip 8.1.1
- python 3.5.2

I'm didn't expect this to work anyway, Python seems to have sticky problems with TLS everywhere its version 2 is bundled with a system.

**Comment by batuhaniskr** [comment]
Can you try with python 3.6.2 or higher version? 

I added create default ssl context for 3.6 and less verion but not resolved result.

**Comment by tobozo** [comment]
@batuhaniskr thanks for your answer :+1: 

I had the same results after upgrading to python 3.6.7 + reinstalling, *however* after upgrading pip from 8.11 to 18.1 it seems to give some results

now I'm experiencing redundancy, as if the pagination is broken our cycling through

![image](https://user-images.githubusercontent.com/1893754/47512113-d0c5c880-d87b-11e8-8315-45db2a16bfd4.png)

do you want me to open a different issue for that?

**Comment by devil67** [comment]
Yeah good man this tool work very well thanks.I've upgrade python3 to Python 3.7.1 and pip to 18.1
